/// Quotes to show randomly
const quotes = [
  "Dream big, start small, act now.",
  "Silence is the best reply to fools.",
  "Stars can’t shine without darkness.",
  "Do it with passion or not at all.",
  "Stay low, keep moving, and strike hard.",
  "You are your only limit.",
  "Hustle until your haters ask if you’re hiring.",
  "Good vibes attract good lives.",
  "Be the energy you want to attract.",
  "Doubt kills more dreams than failure ever will.",
  "Work hard in silence, let success make the noise.",
  "Discipline is stronger than motivation.",
  "Turn the pain into power.",
  "The comeback is always stronger than the setback.",
  "Do what scares you until it doesn’t.",
  "Winners focus on winning, losers focus on winners.",
  "Don’t adapt to the energy in the room; influence it.",
  "Be addicted to bettering yourself.",
  "Every scar tells a story of survival.",
  "The harder the grind, the sweeter the success.",
  "Excuses don’t build empires.",
  "Success hits different when no one believed in you.",
  "Fear is temporary, regret is forever.",
  "Consistency beats talent every time.",
  "Stay hungry, stay humble.",
  "Your vibe is your tribe.",
  "Prove yourself to yourself, not others.",
  "Don’t chase, attract.",
  "A calm mind is a powerful weapon.",
  "What you think, you become.",
  "Grind now, shine later.",
  "Fall seven times, stand up eight.",
  "Your silence has power.",
  "Great things take time — be patient.",
  "Stay focused, stay fearless.",
  "The storm will pass, keep walking.",
  "The best revenge is massive success.",
  "Let your success be your noise.",
  "Every day is a second chance.",
  "Stay mysterious, stay real.",
  "Never let comfort kill your ambition.",
  "When nothing goes right, go left.",
  "Don’t wait for opportunity, create it.",
  "Move in silence, build in private."
];
